### ISSUE TITLE
CMS5 support for DynamoDB

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-dynamodb#45]
Note: Crossed out acceptance criteria represent criteria that simply no longer apply (e.g. there's no deprecated code to remove or throw warnings)

## Acceptance criteria 
- ~Deprecated code is removed in the CMS 5 branch~
- ~Deprecated code throws warning in CMS 4 branch~
- [x] A CMS5 branch is installable
- [x] A CMS5 branch works with PHP8.1/8.2
- [x] GitHub action CI is added to the repo (CMS4 - CMS5)
- [x] A CMS5 beta is tagged
- ~A stable version of CMS4 is tagged (if needed)~
- [x] Shows up in Rino
- [x] Add it to the sink ... if it doesn't break stuff for CCL.

## PRs
- https://github.com/silverstripe/silverstripe-dynamodb/pull/46
- https://github.com/silverstripe/recipe-kitchen-sink/pull/34

**Comment by ChloeSartorelli** [comment]
> A stable version of CMS4 is tagged

Uhhhhh.... why? Shouldn't we do that at the same time as 4.13? And only if there's anything _to_ tag?

**Comment by maxime-rainville** [comment]
We could but ... it's not supported so it's likely we'll forget about it. If there's nothing to tag, then maybe we skip it.

**Comment by ChloeSartorelli** [comment]
We can just add it as an acceptance criteria for the 4.13 release card, and then we won't forget it. But I'm not too fussed since it's not a supported module, technically.
Added "if there are any changes" to tag cms4 ac.

**Comment by emteknetnz** [comment]
Transferred issue to kitchen sink so it appears on our internal board

**Comment by maxime-rainville** [comment]
I've added dynamoDB to the board, so it should have been showing already. 

I'll move it to the backlog for some extra discussion at refinement session Monday.

**Comment by michalkleiner** [comment]
Isn't dynamodb required to run SS on multi-env SCP? Should it therefore be supported?

**Comment by maxime-rainville** [comment]
We'll look at making officially supported once CMS5 is stable. In practice, it is because we test it with every release.

**Comment by ChloeSartorelli** [comment]
There was no deprecated API to remove or stop using.

**Comment by ChloeSartorelli** [comment]
@emteknetnz You told me you've added this to rhino but I can't see it? Can you please link the PR or commit in this issue?

**Comment by ChloeSartorelli** [comment]
PRs merged. https://github.com/silverstripe/silverstripe-dynamodb/pull/48 is now attached to https://github.com/silverstripe/silverstripe-dynamodb/issues/47 instead.
