### ISSUE TITLE
Add tests using local dynamodb instance

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-dynamodb#47]
Currently there are no tests in this module which _actually_ test if it does what it's meant to do (i.e. store sessions in dynamodb)

We should add unit tests which use the [AWS CLI tools](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.CLI.html) with a [local DynamoDB install or docker image](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html) to actually test the functionality of this module.

## Run with the updated ci.yml + dynamodb unit test
**- https://github.com/emteknetnz/silverstripe-dynamodb/actions/runs/4198139701/jobs/7281384647**

## PRs
- https://github.com/silverstripe/silverstripe-dynamodb/pull/48
- https://github.com/silverstripe/gha-ci/pull/57
- https://github.com/silverstripe/silverstripe-dynamodb/pull/49

**Comment by ChloeSartorelli** [comment]
All PRs merged.
