### ISSUE TITLE
Module requires special CI setup

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-dynamodb#52]
Looks like dynamodb wasn't actually running in CI for a long time and now that it ran it's kind of highlighted that it doesn't work in CI for the 5.0 branch.  4.1 branch is fine, though only because it doesn't have test below

Specifically DynamoDbSessionTest::testSessionsAreStoredInDynamoDB() looks like it requires you to actually setup dynamodb in CI, which mean this will need a custom ci.yml file. See the readme.

When doing this, ensure that https://github.com/silverstripe/module-standardiser won't actually override it

Also add in the https://github.com/silverstripe/gha-dispatch-ci workflow

## PRs
- https://github.com/silverstripe/gha-ci/pull/87
- https://github.com/silverstripe/module-standardiser/pull/22
- https://github.com/silverstripe/silverstripe-dynamodb/pull/53
- https://github.com/silverstripe/gha-generate-matrix/pull/68

**Comment by emteknetnz** [comment]
Got dynamodb installing reliably on github actions - https://github.com/emteknetnz/gha-ci/blob/main/.github/workflows/ci.yml

**Comment by ChloeSartorelli** [comment]
PRs merged
